spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJQ2H7DQR7FV6TGDA
  secretKey: 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
  bucketName: student-artifacts-upsilon

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
