server.port: 8080

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

  profiles:
    active: development

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJQ2H7DQR7FV6TGDA
  secretKey: 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
  bucketName: student-artifacts-upsilon

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies